# Generated by Django 4.2.13 on 2024-05-21 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dcapp', '0002_remove_document_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='file',
        ),
        migrations.AddField(
            model_name='document',
            name='image',
            field=models.ImageField(null=True, upload_to='documents/'),
        ),
    ]
